### ISSUE TITLE
Problem with String.split

### ISSUE THREAD

**Issue by frankbauer** [konsoletyper/teavm-javac#8]
Compiling the following code

````java
public class Main {
  public static void main(String[] args){
    "Hello World".split(" ");        
  }
}
````

generates this error
````
ERROR at Main.java:4 Native method java.lang.Character.obtainDigitMapping$$create()Lorg/teavm/platform/metadata/StringResource; has no implementation
    at java.lang.Character.obtainDigitMapping$$create
    at java.lang.Character.obtainDigitMapping
    at java.lang.Character.getDigitMapping(TCharacter.java:315)
    at java.lang.Character.getNumericValue(TCharacter.java:281)
    at java.lang.Character.digit(TCharacter.java:272)
    at java.lang.Character.digit(TCharacter.java:265)
    at java.util.regex.Lexer.readOctals(TLexer.java:867)
    at java.util.regex.Lexer.movePointer(TLexer.java:465)
    at java.util.regex.Lexer.<init>(TLexer.java:230)
    at java.util.regex.Pattern.compileImpl(TPattern.java:335)
    at java.util.regex.Pattern.compile(TPattern.java:321)
    at java.util.regex.Pattern.compile(TPattern.java:1273)
    at java.lang.String.split(TString.java:648)
````

**Comment by frankbauer** [comment]
;)
Could you point me into a direction where I could start to fix this issue?

**Comment by konsoletyper** [comment]
No, I can't do that. Moreover, it's quite hard to properly implement this in sandbox. If you really need String.split, run TeaVM via Maven. I'll definitely make String.split work, as well as many missing methods, but not in this life.
